apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-fix-engine
  namespace: globeco
  labels:
    app: globeco-fix-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-fix-engine
  template:
    metadata:
      labels:
        app: globeco-fix-engine
    spec:
      containers:
        - name: globeco-fix-engine
          image: <IMAGE_PLACEHOLDER>
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 240
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globeco-fix-engine
  namespace: globeco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-fix-engine
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 