apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-fix-engine
  namespace: globeco
  labels:
    app: globeco-fix-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-fix-engine
  template:
    metadata:
      labels:
        app: globeco-fix-engine
    spec:
      containers:
        - name: globeco-fix-engine
          image: kasbench/globeco-fix-engine:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 240
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          # startupProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 30
