apiVersion: v1
kind: Service
metadata:
  name: globeco-fix-engine-service
  namespace: globeco
  labels:
    app: globeco-fix-engine-service
spec:
  selector:
    app: globeco-fix-engine-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP 